-- Factor Factory Webapp Database Init Script
-- Run this script to create the database and initial admin user

CREATE DATABASE IF NOT EXISTS factor_factory
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE factor_factory;

-- Tables will be auto-created by JPA (ddl-auto: update)
-- This script only creates the initial admin user
-- Password: admin123 (BCrypt encoded)
-- Note: The actual BCrypt hash will be generated by the application on first startup
-- via a DataInitializer component

-- Grant privileges (adjust user/host as needed)
-- GRANT ALL PRIVILEGES ON factor_factory.* TO 'root'@'localhost';
-- FLUSH PRIVILEGES;
